using System;
using System.Collections.Generic;
using System.IO;
using System.Text.Json.Serialization;

namespace Codelyzer.Analysis.Model
{
    public class ProjectWorkspace
    {
        [JsonPropertyName("version")]
        [JsonPropertyOrder(1)]
        public string Version { get; set; } = "1.0";

        [JsonPropertyName("generated-by")]
        [JsonPropertyOrder(2)]
        public string GeneratedBy { get; set; }

        [JsonPropertyName("workspace-name")]
        [JsonPropertyOrder(3)]
        public string ProjectName { get; }

        [JsonPropertyName("workspace-root-path")]
        [JsonPropertyOrder(4)]
        public string ProjectRootPath { get; }

        [JsonPropertyName("source-files")]
        [JsonPropertyOrder(5)]
        public UstList<string> SourceFiles;

        [JsonPropertyName("errors-found")]
        [JsonPropertyOrder(6)]
        public int BuildErrorsCount { get; set; }

        [JsonPropertyName("target-framework")]
        [JsonPropertyOrder(7)]
        public string TargetFramework { get; set; }

        [JsonPropertyName("target-frameworks")]
        [JsonPropertyOrder(8)]
        public List<string> TargetFrameworks { get; set; }

        [JsonPropertyName("external-references")]
        [JsonPropertyOrder(9)]
        public ExternalReferences ExternalReferences { get; set; }

        [JsonPropertyName("source-file-results")]
        [JsonPropertyOrder(10)]
        public UstList<RootUstNode> SourceFileResults;

        [JsonPropertyName("workspace-path")]
        [JsonPropertyOrder(11)]
        public string ProjectFilePath { get; }

        [JsonPropertyName("build-errors")]
        [JsonPropertyOrder(12)]
        public List<String> BuildErrors { get; set; }

        [JsonPropertyName("project-guid")]
        [JsonPropertyOrder(13)]
        public string ProjectGuid { get; set; }
        [JsonPropertyName("project-type")]
        [JsonPropertyOrder(14)]
        public string ProjectType { get; set; }

        public ProjectWorkspace(string projectFilePath)
        {
            SourceFiles = new UstList<string>();
            ProjectFilePath = projectFilePath;
            ProjectRootPath = Path.GetDirectoryName(projectFilePath);
            ProjectName = Path.GetFileNameWithoutExtension(projectFilePath);
            SourceFileResults = new UstList<RootUstNode>();
            GeneratedBy = "Auto generated by the Codelyzer  on: " +
                          DateTime.Now.ToString("dddd, dd MMMM yyyy");
        }

        public bool IsBuildFailed()
        {
            return this.BuildErrorsCount > 0 && (this.SourceFileResults == null || this.SourceFileResults.Count == 0);
        }
    }
}
